### ISSUE TITLE
TipManager: ConflictTracking to avoid tip censoring

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#109]

**Comment by jonastheis** [comment]
This issue is very old and I think with our new tip manager and tip selection it shouldn't really be possible to censor tips/blocks of conflicts. 

### 1. Censoring via weak parents
Our tip manager distinguishes between strong and weak children. A strong tip stays a strong tip as long as it doesn't have any strong children. Therefore, referencing a block with only weak parents can not make this block disappear from other nodes' strong tip pool and thus it would still be selected as a strong tip by nodes.

### 2. Censoring with "bad" children blocks
Creating "bad" children blocks could theoretically lead to a block being removed from the strong tip pool but no viable tips to attach to the given block (or block containing the conflict) anymore. However, in practice this is not possible with our tip manager as we do not include objectively invalid blocks (#90) and the timestamp monotonicity of blocks enforces that a timestamp of children blocks is more recent than its parent. Additionally, the tip manager works in a reactive way: as soon as a tip is removed from the tip pool (for any reason) its parent is potentially added back.

### 3. Censoring with rejected conflicts in children
We currently [do not add blocks voting for rejected conflicts to the tips](https://github.com/iotaledger/iota-core/blob/develop/pkg/protocol/engine/tipselection/v1/tip_selection.go#L177). Therefore, the block can't be censored by adding more (unrelated) conflicts in the future cone of a given block. If the conflicts are undecided (for some nodes) at the time of adding to the tip pool, nodes would still pick them as tips and set a like reference accordingly.
