### ISSUE TITLE
Evil Accounts spammer

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#206]

**Comment by daria305** [comment]
TODO:
 - [x] extend transaction builder in iota.go with accounts
 - [x] simple account spammer, we create new accounts from faucet funds, we do not handle those accounts
 - [ ]  evil spammer should allow to create account and remember it for further usage, and spams
 - [ ] solve bootstrapping with implicit account
 - [x]  account handling tools separated from evil spammer, like `go run . accounts` 
 - [x] solution to keep the state with basic spammer, it creates `wallet.dat` file storing the wallet state
        - both accounts tool and evil spammer use the same accountsWallet read from `wallet.dat` file so we can 
 - [ ] created account that can be used with previous functionality of evil spammer, with alias name we provide in options what account should be used for each spam:
        -      `go run . accounts --create A --amount 100000`
        -      `go run . basic --spammer tx --rate 2 --duration 60s --issuer A` <- here we will use mana from account
 - [x] make sure mana is not lost during block creation for evil spammer: `AllotRequiredManaAndStoreRemainingManaInOutput` might be useful
 - [ ] handle allotment strategies to pay for block issuance:
       - allot exact burnt mana cost, use `BuildAndSwapToBlockBuilder`
       - changing allotment amount, testing negative BIC balance
       - allot in advance for data payload spam 
 - [ ] handle other block types:  validation blocks

Evil spammer fixes:
 - [x] adapt to new outputID calculation principles
 - [ ] calculate the target number of required funds and handle funds requesting for longer spams, in `RequestFreshBigFaucetWallet` and similar functions

Fix issues regarding REST API:
 - [x] fix RMC endpoint nil reference error
 - [x] `BlockMetadata` endpoint and providing statuses does not work properly, need it for Awaiting ForConfirmation functionality of evil spammer
 - [x] Add `slotIndex` to  `BlockIssuer` endpoint to point to specific slot we need the commitment for, so that respnce from `congestion` endpoint always matches

**Comment by daria305** [comment]
Example of planned script usage
```bash
./evil-spammergo \
accounts \
create --alias A --amount 1000 --noBIF true \ # noBIF - creates account that is not able to issue
create --alias B --amount 500 --implicit true \
convert --alias B \  # transition to account from implicit
allot --from A --to B --amount 100 \ # if no from then get mana from faucet output, from can be alias of existing account
update --alias B --bik hexkey --addmana 1000 --addtoken 1000 --expiryslot 15 \
destroy --alias A --expirySlot 15 \ # if no expiry then use soonest possible

delegate --amount 100 --to A --from B \# we dont keep track of non account outputs
stake  --alias A --amount 100 --fixedcost 100 --startepoch 100 --endepoch 120  \ # if no startepoch start sonnest possible epoch, no endEPoch then stake infinitely,

```
