### ISSUE TITLE
TipSelection for validators

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#240]
```[tasklist]
### Tasks
- [ ] Make sure an honest validator does not issue blocks within the same slot ratification period in two conflicting chains.
- [ ] Decide the default value to tip selection timeout and retry interval
```

**Comment by polinikita** [comment]
There are multiple issues related to validation blocks. But, for PoA we can use the existing tip selection algorithm. So, in my opinion, this is not a must-have feature for PoA.

Critical misbehavior:
**1**) Issuing many blocks at the same moment (e.g. the intervals between two issued blocks are shorter than expected). This is the hardest thing to deal with as explained below.
**2**) Issuing blocks on two conflicting slot commitment chains, i.e. there are two blocks issued within ONE slot, but they contain conflicting slot commitments (one commitment is not the extension of the other). 

**Why 1 is bad:**
This can be seen as some sort of spamming since validators have a dedicated queue in the scheduler. There will be already two kinds of mechanisms that incentivize to not do that
1) incentives: rewards will not be given to such an adversarial validator 
2) DRR scheduler: scheduler will not let multiple equivocating blocks go through a given node. 
However, first does not solve the spamming attack. The second comes with a caveat as it can result in orphaning blocks of other validators who were not aware about equivocating blocks and reference one of them (Just imagine an adversarial validator issues `COMMITTEE_SIZE` validation blocks and send to each committee member a distinct one. First, each validator will reference one adversarial block in a new block, but then the new block can become orphaned as the DRR scheduler will block the equivocating block.

So, there must be a mechanism in the consensus protocol itself that resolves the issue. There is a simple solution for that with the help of the tip selection algorithm and blacklisting. 
A validator needs to reference in a new block two equivocating blocks (not necessarily directly) of the adversarial validator and after the new block gets accepted, stop directly referencing the adversarial validator's blocks. Once your block is accepted by other nodes, they will notice equivocating blocks and stop directly referencing the adversarial validator's blocks. This is a kind of blacklisting for validators. The blacklist of the committee can be also committed such that new joining nodes could learn about the adversary and not reference his blocks.

**Comment by Buddh1n1** [comment]
Are orphaned validator blocks really an issue? In contrast to orphaned users' blocks, an orphaned validator block will just delay acceptance by a bit in worst case?

Maybe another quick solution: exclude validator blocks from tip selection in general. It should not create too much overhead with additional edges (relative to the entire DAG).
Should solve 2 aswell (if i understood the issue correctly)

**Comment by polinikita** [comment]
@Buddh1n1 

> Are orphaned validator blocks really an issue? In contrast to orphaned users' blocks, an orphaned validator block will just delay acceptance by a bit in worst case?
yes, this is actually the problem. In the worst case, it is possible to orphan all validation blocks by following this algorithm (sure, for this one needs to know the topology of the network). In that case, nothing will be accepted and everything will be orphaned.
> Maybe another quick solution: exclude validator blocks from tip selection in general. It should not create too much overhead with additional edges (relative to the entire DAG).
The same problem will happen if validators are not directly referencing other validation blocks (but do that indirectly). It will not prevent spamming. The same validator would be able to generate tons of validation blocks (all of them will be referenced by other non-validator nodes and then by validator nodes, eventually accepting)

**Comment by Buddh1n1** [comment]
> The same problem will happen if validators are not directly referencing other validation blocks (but do that indirectly). It will not prevent spamming. The same validator would be able to generate tons of validation blocks (all of them will be referenced by other non-validator nodes and then by validator nodes, eventually accepting)

If you remove validator blocks from the tip selection, there will not be any other "regular" blocks building on top of them either.
Since acceptance is local, missing out on the entire "i saw that you saw that..." ins't really an issue... as soon as a node sees >2/3 votes it will mark the block as accepted and commit to it (which is when we get back the "i saw that you saw that..")

**Comment by jonastheis** [comment]
Closing this issue as it is not needed as described. Instead, separate issues have been created to target specific aspects that have been mentioned in the context of this discussion. 
- #299 
- #308 
- #309
