### ISSUE TITLE
Implicit account creation mechanism

### ISSUE THREAD

**Issue by karimodm** [iotaledger/iota-core#278]
https://hackmd.io/@IF/Sy1ZPiJ2n

**Comment by karimodm** [comment]
Counter-proposal: https://hackmd.io/XnDRu-j5SPm-Ly7SJbp_iw?view

**Comment by PhilippGackstatter** [comment]
Couple of notes from recent discussion.

- The reason we wanted the implicit account mechanism work on the address level is that we didn't want to introduce a special output with special rules for implicit account creation, because exchanges would have to handle that specially. The current requirement that we need stored mana in a newly created implicit account means that is not actually the case. Exchanges can send funds to a regular address without needing to add Mana, while they have to add it for implicit accounts.
- The reason we wanted to have implicit accounts pre-funded with Mana was that users could immediately transition the implicit to an "explicit" or "full" account. We should not hide the required Mana for issuing blocks in the network, so it does not make sense to **require** stored mana on implicit account creation. It is still useful to recommend it and set it as the default in client libraries. To improve usability, we want to lower the RMC Min value so a default block in an uncongested network does not mean a long waiting time.
- An important thing to note here is that once there are Mana Marketplaces and/or more sophisticated Block Issuance Service Providers in place, we can enable better UX with service providers that can be paid with based tokens. A user would be able to immediately pay base tokens to issue a transaction in a block if they do not have enough Mana. Then users have the choice to wait without paying in base tokens or immediately pay with base tokens to issue a block.
- While it is technically also a "special rule", the storage deposit of Implicit Account Creation Addresses should be the minimum storage deposit of a default block issuer account (computed value based on protocol parameters) to ensure users can make the transition to explicit accounts for one, but more importantly, to protect the accounts ledger. Since accounts are tracked in the accounts ledger, we need a minimum amount of base tokens to prevent dust. Compared to having Stored Mana in the implicit account for a better onboarding experience, this is a mandatory requirement.
- One can reduce the waiting time for implicit account creation by receiving more funds on a regular, non-implicit-account-creation address, to speed up the potential mana accumulation or even receive stored mana there, the latter of which kind of implies Mana marketplaces.
- Throughput in the scheduler is based on the potential mana and stored mana in an implicit/explicit account. Storage Deposit does not generate potential mana, so it also does not generate throughput. If one has the minimum storage deposit on an implicit account and no stored mana, the throughput would be 0. However we can change the scheduler to still schedule a block with 0 potential/stored mana during uncongested times. That means the implicit account can be used to issue blocks, but the mana to allot to the account in order for it to not go negative must come from elsewhere, e.g. another basic output consumed in the transaction.
- Account Creation in Firefly
    - Input seed phrase. If user does not have an account...
        - ...and user has funds:
            - Use Block Issuance Service Provider.
        - ...and user does not have funds:
            - Use Implicit Account Creation Flow.
- Technicalities
    - One can use the implicit account to issue any kind of block as it is a full block issuer account, so it is possible to issue blocks containing transactions other than the account-creating transaction, however we should not encourage using it that way.
    - On the input side of any transaction there must be exactly 0 or 1 implicit account creation addresses. One **must not be able** to add multiple implicit accounts on the input side of a transaction, from the same or different implicit account creation addresses.
        - One can however use any other non-implicit-account-output, for instance, to get additional funds or Mana into the account-creating TX.
    - One can create an _AccountAddress_ from the implicit account, but one cannot unlock outputs on that address until the full account is created, so it should never be used until that time.
    - If Burned Mana on Block and Alloted Mana in TX match, the account never goes negative, therefore we don't need a protocol built-in mechanism for accounts with negative BIC to unlock themselves automatically.
