### ISSUE TITLE
Improve Indexer API for wallet usecases

### ISSUE THREAD

**Issue by alexsporn** [iotaledger/iota-core#342]

**Comment by Thoralf-M** [comment]
These are the requests that are currently sent by default for a single address to get all outputs that it might can unlock:
```
api/indexer/v1/outputs/basic?address=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g
api/indexer/v1/outputs/basic?expirationReturnAddress=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g
api/indexer/v1/outputs/basic?storageDepositReturnAddress=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g
api/indexer/v1/outputs/nft?address=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g
api/indexer/v1/outputs/nft?expirationReturnAddress=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g
api/indexer/v1/outputs/nft?storageDepositReturnAddress=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g
api/indexer/v1/outputs/alias?governor=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g
api/indexer/v1/outputs/alias?stateController=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g
```

A generic outputs endpoint for all output types could reduce it to a single request if the filtering with the query params is done with `OR` instead of `AND`.
So for example
`api/indexer/v1/outputs?address=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g`
would replace 
`api/indexer/v1/outputs/basic?address=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g` and
`api/indexer/v1/outputs/nft?address=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g`
and
`api/indexer/v1/outputs?address=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g&expirationReturnAddress=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g&storageDepositReturnAddress=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g&governor=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g&stateController=rms1qzcktle67rey5464tenqruxt44004pz2mcd5apydhs8fp0e0l6xl2szjf9g`
would replace all requests above

**Comment by alexsporn** [comment]
Implemented some new filtering options in the stardust version that can easily be ported to the new iota-core version. See https://github.com/iotaledger/inx-indexer/pull/131
