### ISSUE TITLE
Basic blocks issued by validators

### ISSUE THREAD

**Issue by cyberphysic4l** [iotaledger/iota-core#461]
When a validator account issues a basic block, should that carry weight? Or should only Validation blocks carry weight?

Currently, basic blocks issued by validator **do** carry weight.

Summary of discussion:
- [ ] Remove tracking of witness weight and approval weight from basic blocks issued by validators.

**Comment by piotrm50** [comment]
I think it doesn't hurt if they propagate at least witness weight, since even through a BasicBlock they acknowledge the existence of their past cone - and that's how we define witness weight iirc. 

For approval weights on conflicts however it's a little more tricky, because basic blocks might not have enough slots for parents to resolve all the conflicts in their past cones and correctly assign weight, therefore switching their vote on some conflicts - this might be dangerous for the validators as this might be seen as acting maliciously and be penalized.
For this reason I think that basic blocks should not carry approval weight.

The rewards calculation definitely should not consider basic blocks because of the above. 

Now the question is: is it ok if basic blocks only carry witness weight but not approval weight? Or is it better to have it consistent and not carry any weight on basic blocks?

**Comment by cyberphysic4l** [comment]
I think it is cleanest to simply have only validation blocks carry witness and approval weight, and basic blocks carry none.

**Comment by jonastheis** [comment]
> I think it is cleanest to simply have only validation blocks carry witness and approval weight, and basic blocks carry none.

Agree on this.

I think the only change necessary for this would be in the ledger, specifically here: https://github.com/iotaledger/iota-core/blob/ac23b3918bba1a505a3a1984bf5cacc01a53cd6c/pkg/protocol/engine/ledger/ledger/ledger.go#L751

There a check similar to the one already performed in the block gadget (thus currently weight should not be tracked for basic blocks for witness weight) should suffice. https://github.com/iotaledger/iota-core/blob/ac23b3918bba1a505a3a1984bf5cacc01a53cd6c/pkg/protocol/engine/consensus/blockgadget/thresholdblockgadget/gadget.go#L99

**Comment by karimodm** [comment]
Ok, we all agreed that only validation blocks should count for weight (witness and acceptance),
