### ISSUE TITLE
More accounts & validator tests

### ISSUE THREAD

**Issue by cyberphysic4l** [iotaledger/iota-core#466]
More end to end accounts tests are required to ensure everything is working in the VM and accounts manager. 

The tests should focus on user stories, with sequences of actions that we expect for account holders of all kinds. [This PR](https://github.com/iotaledger/iota-core/pull/448) introduces a wallet-centric framework for testing which should facilitate these sequences of account manipultations more intuitively.

**Comment by PhilippGackstatter** [comment]
- Test that Reward Inputs can point to an account id that does not exist or has no rewards in the rewards data. When fetching rewards for accounts that don't exist (or have no rewards) the node should return 0 rather than an error. This is because reward inputs are **required** for removing a Staking Feature from an Account or for destroying a Delegation Output. Otherwise, if I delegated to some address that doesn't exist, I could not destroy my delegation output because the reward would error. (I haven't verified whether this is already implemented as-is or not, but it should be tested regardless).
- Test that Reward Inputs can only point to Accounts & Delegation Outputs. I tried to quickly find that this is checked somewhere but couldn't, so perhaps it's missing.
- Test that a transaction fails whenever the condition for claiming is not given. That is, coming up with scenarios where claiming is **not** allowed and try to claim (remove staking feature, destroy delegation output).
- Test the interplay of accounts with delegation in iota-core, e.g.:

```
// Step 1

Create Delegation Output A delegating to X

// Step 2 (separate epoch)

Create Account X with Staking Feature
Create Delegation Output B delegating to X
Create Delegation Output C delegating to X
Create Delegation Output D delegating to X

In this test X is never selected as a validator. Any Delegation Output that is destroyed should claim 0 rewards.

Assert expectations: X's total stake should be X + A + B + C + D. (I.e. make sure that A is counted even though it was created before X created its staking feature).

// Step 3

Destroy A
Create Delegation Output E delegating to X

Assert expectations: X's total stake should be X + B + C + D + E.

// Step 4

Transition B to Delayed Claiming.
Destroy C.

Assert expectations: X's total stake should be X + D + E.

// Step 5

Destroy Account.

Assert expectations: X should be removed from the "staking tracking data" (not sure what it's called exactly).

// Step 6

Destroy B, D & E.

Assert expectations.
```

Further variations of this test may be to check that removing the staking feature and re-adding it in the same transaction also correctly sets the rewards data and changed start and end epoch of the staker.

**Comment by alexsporn** [comment]
Test BIC going negative, account is blocked and then unblocked by being funded from another tx again.

**Comment by piotrm50** [comment]
> Test BIC going negative, account is blocked and then unblocked by being funded from another tx again.

I take this one.

**Comment by PhilippGackstatter** [comment]
Add test for the case where `End Epoch < Start Epoch` in Delegation Outputs, as depicted here: https://github.com/iotaledger/tips/blob/tip40/tips/TIP-0040/tip-0040.md#start-and-end-epoch.
~~This might lead to a panic currently and should be fixed.~~
Edit: Tested in #551.
