### ISSUE TITLE
Semantic Invalid TX block should be booked and forwarded

### ISSUE THREAD

**Issue by cyberphysic4l** [iotaledger/iota-core#580]
Currently, a **semantic** invalid block will not be booked, and hence it will not be forwarded and the block will never be accepted, so the issuer of the block will not pay any Mana. 

This should be changed to not book the transaction but book the block and forward it as normal.

A block containing an invalid transaction should be picked up as a Weak parent in tip selection as part of standard tip selection procedure.

**Comment by PhilippGackstatter** [comment]
When implementing this issue, [this test](https://github.com/iotaledger/iota-core/blob/aefe705aee38bd8880c3104ea00b76a72ee95881/pkg/tests/reward_test.go#L254-L255) should be updated.

Edit: Might even be better to change the `ts.Wait` to `CommitUntilSlot`. This currently fails, perhaps because the block with the invalid TX cannot get committed on all nodes because the block is not forwarded to all nodes.
