### ISSUE TITLE
Retainer needs to update the transaction metadata for all attachments

### ISSUE THREAD

**Issue by muXxer** [iotaledger/iota-core#588]
The transaction metadata should always be the same, no matter which block you are asking for, so we need to update the transaction metadata for all attachments.
Should we change the retainer storage for that, so we don't have to write the block metadata again?

Is "updating all attachments" actually an amplification attack vector?

**Comment by muXxer** [comment]
We need to decide when to shrink the slot for txID map.

**Comment by daria305** [comment]
**What we have access to:**
When we add block to the Retainer it might be  with event `onBlockAttached` or  method `RetainBlockFailure` we have the access to `model.Block`, so we can see also the `TransactionID`.
We have also a data locality, so from the `TransactionID` we can read the slot of the transaction. The same for the `BlockID`. 

1. Storing `TransactionMetadata` once.
Block metadata
If we store `transactionMetadata` under `transactionSlotID`, block is filtered and we reattach the transaction in some of the next slots, there will be a time, when transaction will be already pruned, but block metadata not. Though user will not be able to get the transaction status.

3. Storing many versions of `TransactionMetadata`, one per block (this is how it was done before)
Problem with this approach is that we need to find a way that all those copies of `TransactionMetadata` will be the same, so whenever a new attachment is added, we need to iterate over all of Transaction's attachments and update. This means the Retainer itself would need to keep its own list of all know attachments per transaction, as the node does not track the attachments that failed.
Then, in this scenario we need to have map, that will be somehow pruned and populated if the node restarts.

4. **First idea.**
With the first version of `feat/retainer` PR I went with 1. way and to prune the transaction metadata not sooner than block `meatadata` I kept `TransactionMetadata` under `latestAttachmentSlot`. To keep track of where in the storage Retainer should look for `TransactionMetadata` I have added:
`transactionLatestAttachmentSlot *shrinkingmap.ShrinkingMap[iotago.TransactionID, iotago.SlotIndex]`
The problem is how to prune this map.

5. **Solution?**: modify the first idea by storing `TransactionMetadata` in `EpochStore` and getting rid of `transactionLatestAttachmentSlot` mapping.
 - Assuming the epochs are very long compared to slots.
- Also, the question is if keeping data for the whole epoch is fine. 
-  I remember that we were planing anyway on storing everything by Epoch. So there would be no point in designing any slot based complicated solution.
From `blockID` and `transactionID` we can read `epochIndex`, or we can simply start from current epoch.

As Epochs are much larger, if we store by Epoch we will usually store everything in the current epoch or at most current and previous one.

We modify the First Idea, by moving `transactionStore` to epoch storage.
When we set transaction metadata for `txID`:
```
	IF `meta`, `found` := `GetTransactionMeatadata`; `found` {
		IF  `epoch(txID)` > `meta.epoch` {
		`// move tx to the latest epoch, similar in the previous solution we did for slot`
			`moveTransactionMeatadata`(`meta.epoch`, `epoch(txID)` )
			}
	}
```
The key difference is that when getting `TransactionMetadata` from storage we don't need any mapping.
In `GetTransactionMeatadata` we can simply iterate from `start = max(currentLocalClockEpoch, transactionEpoch)` to the past epoch, stopping at the pruned epoch. For pruning periods=one epoch, this should be one or max three iterations (when we are close to epoch boundaries).

This solution seems cleaner, as we do not touch pruning mechanism, we just need to make sure that the transaction metadata is stored at least as long as `blockMeatadata`, not sure if it is also worth to move `blockMeta` to the epoch-based storage, but it's rather matter of how long we want to keep also the block metadata.

Instead of iterating over attachments, or slots we sometimes will need to load and try next storage. The worst case is that is user gets asking for some already pruned blocks each time we iterate all three times, or more if epochPruning would be larger. 
We could also combine epoch pruning with duplicated storage of transactions. Always store transaction metadata under block's epoch -> thus any get will be directly checking correct epoch store. Then we would iterate on any update to transaction `meatadata`, on `onTransactionAccepted` event and whenever any attachment gets confirmed.

**Comment by PhilippGackstatter** [comment]
> modify the first idea by storing TransactionMetadata in EpochStore and getting rid of transactionLatestAttachmentSlot mapping.

I think that moving the `transactionStore` to be epoch- rather than slot-based is problematic. Suppose we have a slot commitment chain from slots 0 to 20. If we fork at slot 15, then currently, the transactions in slots 16 to 20 would be deleted during the rollback. With epoch-based storage however, they would not, since we would not be able to address those slots individually. Hence, if someone requested one of the transaction IDs of the old chain via the API, the retainer would still respond successfully, which is not the behavior we would want. The accurate response would be "Transaction Not Found".

If this is the case, then I think we have to leave `transactionStore` to be slot-based so we can properly roll back individual slots.

## Idea 3

To expand on the explanation of idea 3, the issue is that pruning is currently implemented "outside the retainer". Pruning is implemented by directly deleting files on disk, but there is no such thing as an interface method `Prune(...)` that would be called on the retainer, such that the retainer could implement custom logic when pruning happens. Therefore, in the retainer, we cannot prune `transactionLatestAttachmentSlot` because we have no way of knowing when it happens. In other words, pruning assumes anything that needs to be pruned is stored on disk. In-memory data cannot be pruned with the current approach.

A potential solution that Daria suggested was to emit an `EpochPruned` event from the pruning component, and then react to that event in the retainer to prune the in-memory data. However, that adds even more complexity to the pruning logic which I personally already find non trivial to understand.

## Storage-based Approach

I think the two fundamental requirements we have to deal with regarding `transactionLatestAttachmentSlot` are pruning and forking, which are closely related:
- Pruning means we want to delete data that has become too old.
- Forking means we want to delete data that is too new and does not belong to the new chain.

The best approach I still think is to integrate with the existing pruning mechanism so we do not have to touch that. We could consider something akin to the [CommitteeCandidates Store](https://github.com/iotaledger/iota-core/blob/7ee561c378b228548e41fa93efc44e5b71494f02/pkg/storage/prunable/prunable_slot.go#L59). We pick a single slot within an epoch to get an epoch-level `KVStore`. From that we obtain a `kvstore.TypedStore[iotago.TransactionID, iotago.SlotIndex]` to store what is now in `transactionLatestAttachmentSlot`. That way, pruning is taken care of since the mapping is stored on disk.
For the forking requirement, we need to make sure, that even if we fork across an epoch boundary from say `epoch` to `epoch+1`, that the mapping is not deleted yet. So a safe approach might be to use `attachmentSlotIndex := timeprovider.EndEpoch(epoch+1)` to pass to `p.prunableSlotStore.Get(epoch+1, byteutils.ConcatBytes(attachmentSlotIndex.MustBytes(), kvstore.Realm{epochPrefixTransactionLatestAttachmentSlot}`.
So we would store the mapping for transactions falling into `epoch` in the last slot of `epoch+1` to make sure that even during forking, we would not lose the mapping _too early_. The mapping would therefore be pruned with a delay of 1 epoch, which seems not great, not terrible.

An important implementation detail during forking is this: To stay with the initial forking example, the mapping would still contain the transaction id mappings from slot 16 to 20 even though it should've been rolled back. This is probably fine though:
- If a user requests a transaction from that slot range, it would be successfully mapped to a slot, but the TX would not be found in that slot. Hence the perceived behavior would be "Transaction Not Found" which is what we want.
- If a user reissues a transaction from that slot range in the new chain, the attempt to move the transaction data from the old slot to the new slot would fail (since the old slot would not contain the data, because it was rolled back). This can be handled by checking the error during the transaction data move.
So we would actually want the mapping to be restored from disk even upon forking because it contains the mapping of existing transactions to their respective slot.

Not sure if this has other caveats, but it seems like this might work, as abusive of the storage concept as it may be.

Edit: This probably does not work for the transaction metadata endpoint, where we have to lookup the transaction by its ID in the retainer, in which case we would not know which `KVStore` to load from which epoch.

<details>
<summary>
For an even worse idea...
</summary>
Another actual working (but not necessarily good) solution is to keep <code>transactionLatestAttachmentSlot</code> as an in-memory structure and prune it either by hooking an event emitted by prunable or inform the <code>Retainer</code> in some other way that epochs/slots were pruned. To prune efficiently, we would also keep the reverse mapping, that is <code>map[iotago.SlotIndex][]iotago.TransactionID</code>. When creating a new retainer during forking or when restarting the node, iterate the <code>transactionStore</code> and derive from it the content of <code>transactionLatestAttachmentSlot</code>, i.e. by creating the TX ID -> slot mapping. Here we only need to iterate the keys and iterating the entire store in one go might be reasonably fast. I really don't like this solution very much since we introduce more complexity to how pruning works, we have to keep a reverse mapping as well and we have to iterate storage.
</details>

**Comment by muXxer** [comment]
We agreed on creating two different Retainers.

First, the `BlockRetainer` which is based on the current design with the prunable storage.
Second is the `TransactionRetainer` which will be based on a relational database (SQLite) because that is a better fit for this usecase.
Both components needs to handle Pruning and Chain Switching (Reset method) correctly. We should also add the optional error message mentioned in #697 while we are at it.

We should do test driven development for these components.
The tests should include at least the following scenarios:
- First set object as pending
- Overwrite with new state, check if potential former fields are correctly set/unset.
- Check if values can be retrieved after setting them.
- Reset at forking point and check if state is correctly set (newer objects deleted, old still exist)
- Check if pruning works correctly
- For transaction retainer, check if transaction with invalid signatures do not overwrite the state of transactions with valid signatures.

**Comment by muXxer** [comment]
Increased the StoryPoints from 2 to 7, because we have to rewrite the components and add test cases.

**Comment by muXxer** [comment]
I created a new Issue for the transaction retainer #751

**Comment by muXxer** [comment]
Reduced the StoryPoints to 4 again after creating own issue for the Transaction Retainer.

**Comment by muXxer** [comment]
Superseded by #756 and #751
