### ISSUE TITLE
Check Computed Initial Rewards bits

### ISSUE THREAD

**Issue by cyberphysic4l** [iotaledger/iota-core#636]
@oliviasaa commented on a PR that is now closed https://github.com/iotaledger/iota.go/pull/641 that there should be a check on "Computed Initial Rewards" that it is some number of bits. We need to clarify what this check is and add the check if it is needed or remove the comments that refer to exactly 42 bits.

**Comment by oliviasaa** [comment]
I don't think we need this check anymore; the 'manaSupplySanityCheck' already covers it.
What might be useful to add is a check for the parameters 'Decay Balancing Constant Coefficient' and 'Decay Balancing Constant'; we want 

'Decay Balancing Constant/2^(Decay Balancing Constant Coefficient )'
reasonably close to e (otherwise the 'manaSupplySanityCheck' does not cover the 'Computed Initial Rewards' bits requirements).

We can understand "reasonably close" as like 1% of error.

**Comment by cyberphysic4l** [comment]
Agreed we do not require additional checks, but we reshuffle params so we don't include ManaShareCoefficient and DecayBalancingConstant(Exponent) but instead include the finalReward that is derived from these.
