### ISSUE TITLE
Online comittee at epoch boundaries

### ISSUE THREAD

**Issue by cyberphysic4l** [iotaledger/iota-core#643]
The committee itself has CommitteeInSlot and CommitteeInEpoch methods, but OnlineCommittee does not, so the activityTracker does not make sense on epoch boundaries when the seat occupants change. At present, the same seat numbers remain active when the committee is rotated even though the new committee seats correspond to completely different validators. 

I expect this is an intentional simplification, but perhaps the online committee should be reset when a new epoch begins and the committee rotates because it doesn't make sense to carry over the old active seats from the last epoch. The reset value could be to start with no online committee or start with all online.

**Comment by polinikita** [comment]
This is not a bug as this was done intentionally. The concept of seats was introduced to simplify the logic of everything that happens at epoch boundaries. Now the logic is that "seats make decisions, but not rotating nodes behind them". That's why we check the activity of seats and work under the assumption that ">2/3 (online) seats are occupied by correct nodes". 

The problem is that we have many pending objects from the previous epoch and for some objects, decisions have already been reached in the perception of some (but not all) nodes. This issue is not easy to address correctly (without some kind of rounds, e.g. based on Lamport timestamps).

Resetting the online committee to _no_  is not very good as at the very first moments, the online committee will consist of one validator and completely different decisions might be made because of different perceptions of the very first online validator. Resetting the online committee to _all_  is not good as it halts acceptance in the situation when not many validators are online. But this sounds as a safer option if we will stick with a resetting option. 

I think that the concept of seats allows making a smoother transition across epochs assuming the same level of validator's participation (at least in a situation when there is a big intersection between validators, which will be the case for a long period).

**Comment by piotrm50** [comment]
#650 #648 resolve the concerns around this topic.
