### ISSUE TITLE
Fix mana calculation mismatch in transaction builder

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/iota-core#695]
The node returned mana amount mismatch on the native token creation transaction in `accounttransition_test.go` of docker testframework.

This should not happen after building a transaction with `AllotAllMana` option.

**Comment by muXxer** [comment]
`AllotAllMana` was fixed in https://github.com/iotaledger/iota.go/pull/674.
There was no possibility to check if there is even enough mana to issue the block by using this function.

But I think the problem is the testcase itself. We need a function to expose the available leftover mana in the txbuilder I guess. I will have a look.

**Comment by jkrvivian** [comment]
Solved by https://github.com/iotaledger/iota.go/pull/675
