### ISSUE TITLE
StateMutations tree memory leak

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/iota-core#872]
![Image](https://github.com/iotaledger/iota-core/assets/4007944/962c82af-e1bc-4175-88fb-9946a2699018)

**Comment by jonastheis** [comment]
I investigated this issue with the test/benchmark implemented in 0419fcf2928b060ade90e0eebdb0d5cdf23bd3cb. 

As it turns out, no memory is really leaked. The `state tree` tree within `utxoledger.Manager` is long-lived and we keep adding and removing elements to it. If the ledger state grows to a few million outputs, the tree also grows with it as each output is represented by a leaf. However, the underlying https://github.com/pokt-network/smt tree keeps all nodes in memory even when committing the tree and persisting it to disk (`commit` function). 

I guess this is done to optimize performance. However, with a tree of 1mio elements (`outputIDs` in our case), the data in memory is around 260 MB. 

## Experiments
Because of this observation I started to run experiments with and without re-initializing the tree (there's some magic happening with `extension nodes` representing entire subtrees). The full logs can be found here: 
- [tree-in-memory.log](https://github.com/iotaledger/iota-core/files/14754653/tree-in-memory.log)
- [tree-re-init.log](https://github.com/iotaledger/iota-core/files/14754654/tree-re-init.log)

Most interesting is the last case: append 10k outputs to a tree of size 3mio.

### with re-init
it takes 1.36 seconds and the memory consumed is ok. the count of each object is basically how many nodes/leaves in the tree needed to be touched (rest stays untouched on disk)

```
>>> Running with 10000 outputs, reInit: true
>>> Total outputs: 3010000
>>> Took:  1.358539209s

>>> Memory: ALL                                                                                                                                                                                                 
181047  15.924 MB
smt.innerNode		87030   7.968 MB
smt.lazyNode		69838   4.591 MB
smt.leafNode 		17193   2.320 MB
smt.extensionNode 	 6960   1.044 MB
```

### without re-init
it takes 8.4 seconds and obviously consumes memory for all 3mio + 10k outputs.

```
>>> Running with 10000 outputs, reInit: false
>>> Total outputs: 3010000
>>> Took:  8.407177708s

>>> Memory: ALL                                                                                                                                                                                                 
6758958  779.345 MB
smt.leafNode		3010000  403.293 MB
smt.innerNode		3009999  275.574 MB
smt.extensionNode	 738933  100.476 MB
```

### Result
A little bit unexpected but it looks like if the nodes are in cache the thing is actually doing more work. That leads me to believe that for our use case (a big tree with ~10-50k appends/deletes at once, namely when we commit) it is better to re-init the tree for both memory and runtime. This would then actually lead to a quick spike in memory consumption when we commit and after we committed we should probably already re-init the tree so that the memory can be freed.


## Conclusion
As we can't have the entire tree in memory at all times, so we have either two options: modifying the behavior (or adding another one of commit) to flush the cache or re-initializing the tree. The latter seems much more simple and (surprisingly) yields better results in runtime and as expected memory consumption.
